import fs from 'fs';
import { createPrivateKey, createPublicKey, generateKeyPairSync, sign } from 'crypto';
import path from 'path';

function ensureParentDir(filePath) {
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
}

function asn1Length(length) {
    if (length < 0x80) {
        return Buffer.from([length]);
    }

    const bytes = [];
    let remaining = length;

    while (remaining > 0) {
        bytes.unshift(remaining & 0xff);
        remaining >>= 8;
    }

    return Buffer.from([0x80 | bytes.length, ...bytes]);
}

function asn1(tag, ...parts) {
    const value = Buffer.concat(parts);
    return Buffer.concat([Buffer.from([tag]), asn1Length(value.length), value]);
}

function asn1Integer(value) {
    let bigint = typeof value === 'bigint' ? value : BigInt(value);
    if (bigint === 0n) {
        return asn1(0x02, Buffer.from([0x00]));
    }

    const bytes = [];
    while (bigint > 0n) {
        bytes.unshift(Number(bigint & 0xffn));
        bigint >>= 8n;
    }

    if (bytes[0] & 0x80) {
        bytes.unshift(0x00);
    }

    return asn1(0x02, Buffer.from(bytes));
}

function asn1BitString(value) {
    return asn1(0x03, Buffer.from([0x00]), value);
}

function asn1Null() {
    return Buffer.from([0x05, 0x00]);
}

function asn1Oid(oid) {
    const parts = oid.split('.').map(part => Number(part));
    const first = 40 * parts[0] + parts[1];
    const encoded = [first];

    for (const part of parts.slice(2)) {
        let value = part;
        const stack = [value & 0x7f];
        value >>= 7;
        while (value > 0) {
            stack.unshift(0x80 | (value & 0x7f));
            value >>= 7;
        }
        encoded.push(...stack);
    }

    return asn1(0x06, Buffer.from(encoded));
}

function asn1Utf8String(value) {
    return asn1(0x0c, Buffer.from(value, 'utf8'));
}

function asn1UtcTime(date) {
    const year = date.getUTCFullYear() % 100;
    const month = String(date.getUTCMonth() + 1).padStart(2, '0');
    const day = String(date.getUTCDate()).padStart(2, '0');
    const hour = String(date.getUTCHours()).padStart(2, '0');
    const minute = String(date.getUTCMinutes()).padStart(2, '0');
    const second = String(date.getUTCSeconds()).padStart(2, '0');

    return asn1(0x17, Buffer.from(`${String(year).padStart(2, '0')}${month}${day}${hour}${minute}${second}Z`, 'ascii'));
}

function asn1Sequence(...parts) {
    return asn1(0x30, ...parts);
}

function asn1Set(...parts) {
    return asn1(0x31, ...parts);
}

function asn1Explicit(tagNumber, ...parts) {
    return asn1(0xa0 + tagNumber, ...parts);
}

function encodeName(commonName) {
    return asn1Sequence(asn1Set(asn1Sequence(asn1Oid('2.5.4.3'), asn1Utf8String(commonName))));
}

function encodeAlgorithmIdentifier() {
    return asn1Sequence(asn1Oid('1.2.840.113549.1.1.11'), asn1Null());
}

function encodeValidity() {
    const now = new Date();
    const notBefore = new Date(now.getTime() - 5 * 60 * 1000);
    const notAfter = new Date(now.getTime() + 365 * 24 * 60 * 60 * 1000);

    return asn1Sequence(asn1UtcTime(notBefore), asn1UtcTime(notAfter));
}

export function generateSelfSignedCert(certPath, keyPath) {
    ensureParentDir(certPath);
    ensureParentDir(keyPath);

    const { privateKey } = generateKeyPairSync('rsa', {
        modulusLength: 4096,
        publicExponent: 0x10001,
        privateKeyEncoding: {
            format: 'pem',
            type: 'pkcs1'
        }
    });

    const privateKeyObject = createPrivateKey(privateKey);
    const publicKeyDer = createPublicKey(privateKeyObject).export({
        format: 'der',
        type: 'spki'
    });

    const certificateBody = asn1Sequence(
        asn1Explicit(0, asn1Integer(2)),
        asn1Integer(0),
        encodeAlgorithmIdentifier(),
        encodeName('Grumble Autogenerated Certificate'),
        encodeValidity(),
        encodeName('Grumble Autogenerated Certificate'),
        publicKeyDer
    );

    const signature = sign('sha256', certificateBody, privateKeyObject);
    const certificateDer = asn1Sequence(certificateBody, encodeAlgorithmIdentifier(), asn1BitString(signature));
    const certificate = `-----BEGIN CERTIFICATE-----\n${certificateDer
        .toString('base64')
        .match(/.{1,64}/g)
        .join('\n')}\n-----END CERTIFICATE-----\n`;

    fs.writeFileSync(certPath, certificate);
    fs.writeFileSync(keyPath, privateKey);
}
